on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: ''

jobs:
  build-test-publish:
    name: 'Main Pipeline'
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup :: Checkout'
        uses: actions/checkout@v3

      - name: 'Setup :: Determine Node version'
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: 'Setup :: Node'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 'Application :: Install Dependencies'
        run: npm install

      - name: 'Application :: Build'
        run: npm run build

      - name: 'QA :: Unit Tests'
        run: npm run test

      - name: 'Deployment :: Publish to NPM'
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm publish --access public
          npm config delete //registry.npmjs.org/:_authToken
