on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_MAJOR_VERSION: ''

jobs:
  build-test-publish:
    name: 'Main Pipeline'
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup :: Checkout'
        uses: actions/checkout@v4

      - name: 'Setup :: Determine Node version'
        run: echo "NODE_MAJOR_VERSION=$(grep node .tool-versions | awk '{ print $2 }' | awk -F. '{ print $1 }')" >> $GITHUB_ENV

      - name: 'Setup :: Node'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_MAJOR_VERSION }}
          cache: 'npm'

      - name: 'Application :: Install Dependencies'
        run: npm install

      - name: 'Application :: Build'
        run: npm run build

      - name: 'QA :: Unit Tests'
        run: npm run test

      - name: 'Release :: Set Version'
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Releasing: $GITHUB_REF_NAME"
          npm version $GITHUB_REF_NAME --git-tag-version false

      - name: 'Deployment :: Publish to NPM'
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm publish --access public
